### ISSUE TITLE
Another way to save changes?

### ISSUE THREAD

**Issue by tbnv** [PeachScript/sketch-plugin-monster#16]
Hi,

Would it be possible to store changes another way than by editing the manifest.json of the corresponding plugins? I manage and update all plugins via Git (I guess I'm not the only one), and Plugin Monster's edits are kind of disturbing the flow. 😉

<img width="1051" alt="5mndccmyymtcnmbxweji" src="https://cloud.githubusercontent.com/assets/1021579/23557784/85b2f2e2-0031-11e7-9f57-726b2cc1e35a.png">

**Comment by PeachScript** [comment]
Aha, it's a tricky problem, because the shortcut will not working correcly if this plugin save changes to other place, but you can solve it by the following two ways:

1. Execute `git stash` command before `git pull`, then execute `git stash pop` after that;
2. I have been released [v0.2.0](https://github.com/PeachScript/sketch-plugin-monster/releases/tag/v0.2.0), you can export your shortcut configurations and upgrade plugin by override then import them, sounds complicated :(

As you said, so many designer upgrade plugins via Git, so we already add `plugin version management` into roadmap when I and my friend plan to create this plugin, perhaps we can upgrade plugin easily in the near future :P

**Comment by PeachScript** [comment]
Sketch will support plugin updates in version 45 and later, and there are already many plugin version management tools, such as `Runner`、`Sketchpacks` and `Sketch Plugin Manager`, so we decided not to make the same feature.

Hope the official plugin system can be more and more powerful :D

**Comment by tbnv** [comment]
The problem was not really about managing plugin versions but the way you store shortcut changes: by editing the plugin files, which triggers a change in the git repo. Anyway, it totally makes sens that you don't support plugin updates since it will be included in Sketch by default.

**Comment by PeachScript** [comment]
Because of the Sketch will read `manifest.json` file and set shortcuts through the file for each plugin, so I cannot change the way to save shortcut changes.

I had hoped to solve the shortcuts lost problem with the plugin version manage feature, because the problem caused basically by plugin upgrade, so it can be processed when the plugin upgrading. For now, without plugin version manage feature, if you still upgrade plugin versions by `Git`, you can try the first way of [my first comment](https://github.com/PeachScript/sketch-plugin-monster/issues/16#issuecomment-284037493) in this issue, if you upgrade plugin version by `Runner` or official way, you can solve this problem through the shortcuts exports and import feature in `Plugins -> Sketch Plugin Monster -> Export/import shortcuts configurations`. 

In the future, I believe the Sketch team will solve this problem in a better way, [discuss details](http://sketchplugins.com/d/229-updating-plugins/13).
